# Generated by Django 5.2.6 on 2026-02-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_question_topic'),
        ('lms', '0003_goethe'),
    ]

    operations = [
    ]
