# Generated by Django 5.2.6 on 2026-02-21 16:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_merge_0002_question_topic_0003_goethe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goetheexam',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='goetheexamrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='goetheexamrequest',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='Set automatically when instructor forwards the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goethe_forwarded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LessonRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=300)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('alt_date', models.DateField(blank=True, null=True)),
                ('alt_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('student_message', models.TextField(blank=True)),
                ('instructor_note', models.TextField(blank=True)),
                ('zoom_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lesson_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
